"""Added status to Alert

Revision ID: 8f94b003301a
Revises: e055ee426239
Create Date: 2024-10-10 23:57:08.970908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f94b003301a'
down_revision = 'e055ee426239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'status')
    # ### end Alembic commands ###
